<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2017-09-28 14:57:26',
                'updated_at' => '2017-09-28 14:57:26',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2017-09-28 14:57:26',
                'updated_at' => '2017-12-23 05:22:49',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Posts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-photos',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2017-09-28 14:57:26',
                'updated_at' => '2017-09-28 23:04:21',
                'route' => 'voyager.posts.index',
                'parameters' => 'null',
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2017-09-28 14:57:26',
                'updated_at' => '2017-12-23 05:22:49',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2017-09-28 14:57:26',
                'updated_at' => '2017-12-23 05:22:49',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Pages',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2017-09-28 14:57:26',
                'updated_at' => '2017-12-23 05:22:49',
                'route' => 'voyager.pages.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2017-09-28 14:57:26',
                'updated_at' => '2017-12-23 05:22:49',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2017-09-28 14:57:26',
                'updated_at' => '2017-12-23 05:22:49',
                'route' => NULL,
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 1,
                'created_at' => '2017-09-28 14:57:26',
                'updated_at' => '2017-09-28 23:06:07',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 2,
                'created_at' => '2017-09-28 14:57:26',
                'updated_at' => '2017-09-28 23:06:07',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '/admin/compass',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 3,
                'created_at' => '2017-09-28 14:57:26',
                'updated_at' => '2017-09-28 23:06:07',
                'route' => NULL,
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '/admin/hooks',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 8,
                'order' => 4,
                'created_at' => '2017-09-28 14:57:26',
                'updated_at' => '2017-09-28 23:06:07',
                'route' => NULL,
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2017-09-28 14:57:26',
                'updated_at' => '2017-12-23 05:22:49',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Themes',
                'url' => '/admin/themes',
                'target' => '_self',
                'icon_class' => 'voyager-paint-bucket',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2017-09-28 22:57:30',
                'updated_at' => '2017-12-23 05:22:49',
                'route' => NULL,
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 2,
                'title' => 'Home',
                'url' => '/',
                'target' => '_self',
                'icon_class' => 'fa fa-home',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2017-12-14 17:45:26',
                'updated_at' => '2017-12-14 17:47:24',
                'route' => NULL,
                'parameters' => '',
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 2,
                'title' => 'Popular',
                'url' => '/#_',
                'target' => '_self',
                'icon_class' => 'fa fa-star',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2017-12-14 17:45:59',
                'updated_at' => '2017-12-14 17:47:24',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 2,
                'title' => 'for the Week',
                'url' => '/popular/week',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 16,
                'order' => 1,
                'created_at' => '2017-12-14 17:46:48',
                'updated_at' => '2017-12-14 20:39:11',
                'route' => NULL,
                'parameters' => '',
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 2,
                'title' => 'for the Month',
                'url' => '/popular/month',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 16,
                'order' => 2,
                'created_at' => '2017-12-14 17:46:59',
                'updated_at' => '2017-12-14 17:47:25',
                'route' => NULL,
                'parameters' => '',
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => 2,
                'title' => 'for the Year',
                'url' => '/popular/year',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 16,
                'order' => 3,
                'created_at' => '2017-12-14 17:47:10',
                'updated_at' => '2017-12-14 17:47:28',
                'route' => NULL,
                'parameters' => '',
            ),
            19 => 
            array (
                'id' => 20,
                'menu_id' => 2,
                'title' => 'All Time',
                'url' => '/popular',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 16,
                'order' => 4,
                'created_at' => '2017-12-14 17:47:21',
                'updated_at' => '2017-12-14 17:47:29',
                'route' => NULL,
                'parameters' => '',
            ),
            20 => 
            array (
                'id' => 21,
                'menu_id' => 2,
                'title' => 'Categories',
                'url' => '/#_',
                'target' => '_self',
                'icon_class' => 'fa fa-list',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2017-12-14 17:48:05',
                'updated_at' => '2017-12-14 17:48:48',
                'route' => NULL,
                'parameters' => '',
            ),
            21 => 
            array (
                'id' => 22,
                'menu_id' => 2,
                'title' => 'Animals',
                'url' => '/category/animals',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 1,
                'created_at' => '2017-12-14 17:48:29',
                'updated_at' => '2017-12-14 17:48:48',
                'route' => NULL,
                'parameters' => '',
            ),
            22 => 
            array (
                'id' => 23,
                'menu_id' => 2,
                'title' => 'Architecture',
                'url' => '/category/architecture',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 2,
                'created_at' => '2017-12-14 17:48:43',
                'updated_at' => '2017-12-14 17:48:50',
                'route' => NULL,
                'parameters' => '',
            ),
            23 => 
            array (
                'id' => 24,
                'menu_id' => 2,
                'title' => 'Cartoon',
                'url' => '/category/cartoon',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 3,
                'created_at' => '2017-12-14 17:49:06',
                'updated_at' => '2017-12-14 17:49:36',
                'route' => NULL,
                'parameters' => '',
            ),
            24 => 
            array (
                'id' => 25,
                'menu_id' => 2,
                'title' => 'Comedy',
                'url' => '/category/comedy',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 4,
                'created_at' => '2017-12-14 17:49:25',
                'updated_at' => '2017-12-14 17:49:37',
                'route' => NULL,
                'parameters' => '',
            ),
            25 => 
            array (
                'id' => 26,
                'menu_id' => 2,
                'title' => 'Comics',
                'url' => '/category/comics',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 5,
                'created_at' => '2017-12-14 17:49:53',
                'updated_at' => '2017-12-14 17:51:51',
                'route' => NULL,
                'parameters' => '',
            ),
            26 => 
            array (
                'id' => 27,
                'menu_id' => 2,
                'title' => 'Family',
                'url' => '/category/family',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 6,
                'created_at' => '2017-12-14 17:50:05',
                'updated_at' => '2017-12-14 17:51:54',
                'route' => NULL,
                'parameters' => '',
            ),
            27 => 
            array (
                'id' => 28,
                'menu_id' => 2,
                'title' => 'Film',
                'url' => '/category/film',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 7,
                'created_at' => '2017-12-14 17:50:20',
                'updated_at' => '2017-12-14 17:51:55',
                'route' => NULL,
                'parameters' => '',
            ),
            28 => 
            array (
                'id' => 29,
                'menu_id' => 2,
                'title' => 'Food',
                'url' => '/category/food',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 8,
                'created_at' => '2017-12-14 17:50:31',
                'updated_at' => '2017-12-14 17:51:56',
                'route' => NULL,
                'parameters' => '',
            ),
            29 => 
            array (
                'id' => 30,
                'menu_id' => 2,
                'title' => 'Music',
                'url' => '/category/music',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 9,
                'created_at' => '2017-12-14 17:50:42',
                'updated_at' => '2017-12-14 17:51:58',
                'route' => NULL,
                'parameters' => '',
            ),
            30 => 
            array (
                'id' => 31,
                'menu_id' => 2,
                'title' => 'News',
                'url' => '/category/news',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 10,
                'created_at' => '2017-12-14 17:50:56',
                'updated_at' => '2017-12-14 17:51:59',
                'route' => NULL,
                'parameters' => '',
            ),
            31 => 
            array (
                'id' => 32,
                'menu_id' => 2,
                'title' => 'Retro',
                'url' => '/category/retro',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 11,
                'created_at' => '2017-12-14 17:51:08',
                'updated_at' => '2017-12-14 17:52:00',
                'route' => NULL,
                'parameters' => '',
            ),
            32 => 
            array (
                'id' => 33,
                'menu_id' => 2,
                'title' => 'Sports',
                'url' => '/category/sports',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 12,
                'created_at' => '2017-12-14 17:51:20',
                'updated_at' => '2017-12-14 17:52:01',
                'route' => NULL,
                'parameters' => '',
            ),
            33 => 
            array (
                'id' => 34,
                'menu_id' => 2,
                'title' => 'Uncategorized',
                'url' => '/category/uncategorized',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 13,
                'created_at' => '2017-12-14 17:51:35',
                'updated_at' => '2017-12-14 17:52:02',
                'route' => NULL,
                'parameters' => '',
            ),
            34 => 
            array (
                'id' => 35,
                'menu_id' => 2,
                'title' => 'Vehicles',
                'url' => '/category/vehicles',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 21,
                'order' => 14,
                'created_at' => '2017-12-14 17:51:46',
                'updated_at' => '2017-12-14 17:52:03',
                'route' => NULL,
                'parameters' => '',
            ),
            35 => 
            array (
                'id' => 36,
                'menu_id' => 1,
                'title' => 'Comments',
                'url' => '/admin/comments',
                'target' => '_self',
                'icon_class' => 'voyager-bubble',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2017-12-18 13:51:18',
                'updated_at' => '2017-12-18 13:56:34',
                'route' => NULL,
                'parameters' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'menu_id' => 1,
                'title' => 'Comment Flags',
                'url' => '/admin/comment-flags',
                'target' => '_self',
                'icon_class' => 'voyager-warning',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2017-12-23 05:16:46',
                'updated_at' => '2017-12-23 05:22:49',
                'route' => NULL,
                'parameters' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'menu_id' => 2,
                'title' => 'More',
                'url' => '#_',
                'target' => '_self',
                'icon_class' => 'fa fa-diamond',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2017-12-26 14:34:10',
                'updated_at' => '2017-12-26 14:59:58',
                'route' => NULL,
                'parameters' => '',
            ),
            38 => 
            array (
                'id' => 39,
                'menu_id' => 2,
                'title' => 'Leaderboard',
                'url' => '/leaderboard',
                'target' => '_self',
                'icon_class' => 'voyager-star',
                'color' => '#000000',
                'parent_id' => 38,
                'order' => 2,
                'created_at' => '2017-12-26 14:34:52',
                'updated_at' => '2017-12-26 15:06:31',
                'route' => NULL,
                'parameters' => '',
            ),
            39 => 
            array (
                'id' => 40,
                'menu_id' => 2,
                'title' => 'Contact',
                'url' => '/page/contact',
                'target' => '_self',
                'icon_class' => '',
                'color' => '#000000',
                'parent_id' => 38,
                'order' => 1,
                'created_at' => '2017-12-26 15:06:27',
                'updated_at' => '2017-12-26 15:06:31',
                'route' => NULL,
                'parameters' => '',
            ),
        ));
        
        
    }
}